"use client"

import React, { useEffect, useState } from "react"
import { useForm, Controller } from "react-hook-form"
import slugify from "slugify"
import styled from "styled-components"
import { theme } from "../../../styles/theme"
import { Modal } from "../../components/ui/Modal"
import { Input } from "../../components/ui/Input"
import { TextArea } from "../../components/ui/TextArea"
import { Button } from "../../components/ui/Button"
import { FormField } from "../../components/ui/FormField"
import { useToast } from "../../components/ToastProvider"
import api from "../../../lib/api"
import { Text } from "../../components/ui/Text"

interface CreateCollectionFormValues {
    name: string;
    slug: string;
    description: string;
}

interface CreateCollectionModalProps {
    isOpen: boolean
    onClose: () => void
    onSubmit: (data: CreateCollectionFormValues) => Promise<void>
}

const Form = styled.form`
  display: flex;
  flex-direction: column;
  width: 100%;
`

const FormActions = styled.div`
  display: flex;
  gap: ${theme.spacing.sm};
  justify-content: flex-end;
  margin-top: ${theme.spacing.md};
`

const ErrorMessage = styled.div`
  background-color: ${theme.colors.error}15;
  border: 1px solid ${theme.colors.error}30;
  border-radius: ${theme.borderRadius.md};
  padding: ${theme.spacing.md};
  margin-bottom: ${theme.spacing.md};
`

const AutogeneratedInput = styled(Input)`
  color: ${theme.colors["muted-foreground"]};
  cursor: not-allowed;
  &:focus {
    border-color: ${theme.colors.border};
    box-shadow: none;
  }
`

const AutogeneratedNote = styled(Text)`
  display: flex;
  align-items: center;
  margin-top: ${theme.spacing.xs};
  svg {
    margin-right: ${theme.spacing.xs};
  }
`

export const CreateCollectionModal: React.FC<CreateCollectionModalProps> = ({
    isOpen,
    onClose,
    onSubmit
}) => {
    const { toast } = useToast()
    const {
        control,
        handleSubmit,
        formState: { isSubmitting },
        watch,
        setValue,
        getValues,
        reset
    } = useForm<CreateCollectionFormValues>({
        defaultValues: {
            name: "",
            slug: "",
            description: ""
        }
    })

    const name = watch("name")
    useEffect(() => {
        if (name) {
            const generatedSlug = slugify(name, {
                lower: true,
                strict: true,
                trim: true
            });
            setValue("slug", generatedSlug);
        } else {
            setValue("slug", "");
        }
    }, [name, setValue])

    const handleFormSubmit = async (data: CreateCollectionFormValues) => {
        if (!data.name || !data.slug) {
            toast({
                title: "Validation Error",
                description: "Name and slug are required fields",
                duration: 5000
            });
            return;
        }

        try {
            await api.post('/kyper/collections/create', data);
            await onSubmit(data);

            toast({
                title: "Collection created",
                description: `Successfully created collection "${data.name}"`,
                duration: 5000
            });

            handleClose();
        } catch (error: any) {
            console.error("Failed to create collection:", error);

            const errorMessage = error.response?.data?.message ||
                error.response?.data?.error ||
                error.message ||
                'An unexpected error occurred';

            toast({
                title: "Failed to create collection",
                description: errorMessage,
                duration: 8000
            });

            if (error.response?.status === 409) {
                toast({
                    title: "Duplicate slug detected",
                    description: "Please modify the collection name to generate a different slug",
                    duration: 6000
                });
            }
        }
    }

    const handleClose = () => {
        reset();
        onClose();
    }

    return (
        <Modal
            isOpen={isOpen}
            onClose={handleClose}
            size="md"
            position="center"
        >
            <Modal.Header
                heading="Create New Collection"
                subheading="Add a new content collection to your CMS"
                onClose={handleClose}
            />

            <Modal.Body>
                <Form noValidate>
                    <FormField
                        label="Name"
                        required
                    >
                        <Controller
                            name="name"
                            control={control}
                            rules={{ required: true }}
                            render={({ field }) => (
                                <Input
                                    {...field}
                                    placeholder="e.g., Blog Posts"
                                    disabled={isSubmitting}
                                    required
                                />
                            )}
                        />
                    </FormField>

                    <FormField
                        label="Slug"
                        description="URL-friendly identifier (automatically generated from name)"
                        required
                    >
                        <Controller
                            name="slug"
                            control={control}
                            rules={{ required: true }}
                            render={({ field }) => (
                                <>
                                    <AutogeneratedInput
                                        {...field}
                                        placeholder="auto-generated-slug"
                                        readOnly
                                        required
                                    />
                                    <AutogeneratedNote type="small" muted>
                                        This field is automatically generated from the name
                                    </AutogeneratedNote>
                                </>
                            )}
                        />
                    </FormField>

                    <FormField
                        label="Description"
                        optional
                    >
                        <Controller
                            name="description"
                            control={control}
                            render={({ field }) => (
                                <TextArea
                                    {...field}
                                    placeholder="Describe what this collection will contain..."
                                    disabled={isSubmitting}
                                    rows={4}
                                />
                            )}
                        />
                    </FormField>
                </Form>
            </Modal.Body>

            <Modal.Footer>
                <Button
                    variant="ghost"
                    onClick={handleClose}
                    disabled={isSubmitting}
                >
                    Cancel
                </Button>
                <Button
                    variant="solid"
                    color="primary"
                    onClick={handleSubmit(handleFormSubmit)}
                    disabled={isSubmitting}
                    loading={isSubmitting}
                    loadingText="Creating..."
                    spinnerType="spinner"
                    type="button"
                >
                    Create Collection
                </Button>
            </Modal.Footer>
        </Modal>
    )
}

CreateCollectionModal.displayName = "CreateCollectionModal"